### ISSUE TITLE
Dashes are being escaped

### ISSUE THREAD

**Issue by huynguye** [msztorc/laravel-env#11]
Hi, when trying to set env variable to a value with a dash, a slash will appear in front of the dash in the .env file.

i.e:
` TEST_VAR=my\-test`

Can you exclude the dash from being escaped?

Thank you.

**Comment by msztorc** [comment]
fixed

**Comment by sourajb** [comment]
Hello,

I have the same issue when trying to set env variable to a value with + or =, a slash will appear in front of the dash in the .env file.

Can you exclude = and + from being escaped?

Thanks.

**Comment by zfm-andreasmatuszewski** [comment]
> Hello,
> 
> I have the same issue when trying to set env variable to a value with + or =, a slash will appear in front of the dash in the .env file.
> 
> Can you exclude = and + from being escaped?
> 
> Thanks.

@msztorc could you also apply this requested change or do you have a workaround for this?

**Comment by msztorc** [comment]
@zfm-andreasmatuszewski reopening this

**Comment by msztorc** [comment]
Fixed in #19

**Comment by msztorc** [comment]
Released v1.3.0
cc: @zfm-andreasmatuszewski  @sourajb
