### ISSUE TITLE
Forces page reload with axios request

### ISSUE THREAD

**Issue by akinsayo** [msztorc/laravel-env#15]
Hi.

When using this package with vuejs 3 (Laravel 9 + Inertiajs + vue), on post of values to change and subsequent change of the values, a page refresh is always forced when the package is used. When turned off, everything works the way it should.

Could you please look into this?

**Comment by msztorc** [comment]
Hi @akinsayo Could you please share more details about this? I understand that problem happens when you use the laravel-env interface programmatically, is that correct? Can you share any code snippets? Thanks!
