### ISSUE TITLE
setValue with value url will error

### ISSUE THREAD

**Issue by inubayuaji** [msztorc/laravel-env#5]
**Problem**
When you want to give the url value to the APP_URL key or another key with the url value the results in the env file will be different.

**Example**
For example, you want to fill in the value `https://google.com` but the result in env file will be `https\://google.com`.

**Cause**
Once I see in the code it is caused by `return preg_quote($value);` in line 143 of file Env.php.

**My Temporary Solution**
I change code from return preg_quote($value);` to return $value;`.

I'm sorry if my English is bad and this is the first issue I raise 🙏

**Comment by dafi-mcisse** [comment]
i have the same problem

**Comment by msztorc** [comment]
This is in progress. Thanks for reporting.
